codecov:
  require_ci_to_pass: false
  token: ${{ secrets.CODECOV_TOKEN }}
  
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        # Only check coverage on main branch
        if_ci_failed: error
    patch:
      default:
        target: 50%  # Lower diff coverage threshold - many changes are config/setup
        threshold: 15%  # Allow 15% variance for diff coverage
        base: auto
        # Only check coverage on main branch  
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

github_checks:
  # Disable check suites to prevent hanging on non-main branches
  annotations: false
