codecov:
  require_ci_to_pass: false
  
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        # Only check coverage on main branch
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto
        # Only check coverage on main branch  
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

github_checks:
  # Disable check suites to prevent hanging on non-main branches
  annotations: false