version: '3.8'

x-webhook-template: &webhook-template
  build: .
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${HOME}/.aws:/root/.aws:ro
    - ${HOME}/.claude-hub:/home/node/.claude
  environment:
    - NODE_ENV=production
    - TRUST_PROXY=true
    - BOT_EMAIL=${BOT_EMAIL:-claude@example.com}
    - DEFAULT_BRANCH=${DEFAULT_BRANCH:-main}
    - CLAUDE_USE_CONTAINERS=1
    - CLAUDE_CONTAINER_IMAGE=claudecode:latest
    - CLAUDE_AUTH_HOST_DIR=${CLAUDE_AUTH_HOST_DIR:-${HOME}/.claude-hub}
    - DISABLE_LOG_REDACTION=true
    - BASH_DEFAULT_TIMEOUT_MS=600000
    - BASH_MAX_TIMEOUT_MS=1200000
    - PR_REVIEW_WAIT_FOR_ALL_CHECKS=true
    - GITHUB_TOKEN=${GITHUB_TOKEN}
    - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    - CLAUDE_WEBHOOK_SECRET=${CLAUDE_WEBHOOK_SECRET}
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 10s

services:
  # Team 1 instance
  webhook-team1:
    <<: *webhook-template
    ports:
      - "3001:3002"
    environment:
      - PORT=3002
      - AUTHORIZED_USERS=team1-user1,team1-user2
      - BOT_USERNAME=@MCPClaude-Team1
      - DEFAULT_GITHUB_OWNER=team1

  # Team 2 instance
  webhook-team2:
    <<: *webhook-template
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - AUTHORIZED_USERS=team2-user1,team2-user2
      - BOT_USERNAME=@MCPClaude-Team2
      - DEFAULT_GITHUB_OWNER=team2

  # Team 3 instance
  webhook-team3:
    <<: *webhook-template
    ports:
      - "3003:3002"
    environment:
      - PORT=3002
      - AUTHORIZED_USERS=team3-user1,team3-user2
      - BOT_USERNAME=@MCPClaude-Team3
      - DEFAULT_GITHUB_OWNER=team3

  # Team 4 instance
  webhook-team4:
    <<: *webhook-template
    ports:
      - "3004:3002"
    environment:
      - PORT=3002
      - AUTHORIZED_USERS=team4-user1,team4-user2
      - BOT_USERNAME=@MCPClaude-Team4
      - DEFAULT_GITHUB_OWNER=team4

  # Team 5 instance
  webhook-team5:
    <<: *webhook-template
    ports:
      - "3005:3002"
    environment:
      - PORT=3002
      - AUTHORIZED_USERS=team5-user1,team5-user2
      - BOT_USERNAME=@MCPClaude-Team5
      - DEFAULT_GITHUB_OWNER=team5

  # Add more teams as needed...

  # Optional: Nginx reverse proxy for nice URLs
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-hackathon.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webhook-team1
      - webhook-team2
      - webhook-team3
      - webhook-team4
      - webhook-team5