apiVersion: v1
kind: Secret
metadata:
  name: claude-webhook-secrets
  namespace: default
type: Opaque
stringData:
  github-token: "YOUR_GITHUB_TOKEN_HERE"
  anthropic-api-key: "YOUR_ANTHROPIC_API_KEY_HERE"
  webhook-secret: "YOUR_WEBHOOK_SECRET_HERE"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claude-webhook
  template:
    metadata:
      labels:
        app: claude-webhook
    spec:
      containers:
      - name: webhook
        image: claude-webhook:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: GITHUB_TOKEN_FILE
          value: "/etc/secrets/github-token"
        - name: ANTHROPIC_API_KEY_FILE
          value: "/etc/secrets/anthropic-api-key"
        - name: GITHUB_WEBHOOK_SECRET_FILE
          value: "/etc/secrets/webhook-secret"
        volumeMounts:
        - name: secrets-volume
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets-volume
        secret:
          secretName: claude-webhook-secrets
          items:
          - key: github-token
            path: github-token
          - key: anthropic-api-key
            path: anthropic-api-key
          - key: webhook-secret
            path: webhook-secret